//
//  SystemPromptDefaultsHistory.swift
//  WhisperShortcut
//
//  GENERATED by scripts/prompt-default-fingerprints.py — do not edit by hand.
//  Re-run the script after changing any AppConstants.default*Prompt constant.
//

import CryptoKit
import Foundation

/// Every wording the shipped default system prompts have ever had, as fingerprints.
///
/// `SystemPromptsStore` materialises the defaults into the user's `system-prompts.md` on first
/// launch and reads only that file afterwards, so a change to a default constant never reached
/// an existing install — even one whose user had not touched the section. This list is how the
/// store tells "never edited" (still equal to some former default) from "edited": the former is
/// lifted to the current default on launch, the latter is left alone.
///
/// Fingerprints are SHA-256 over whitespace-normalised text, so a stray trailing newline or
/// re-wrapped paragraph in the file does not count as a user edit.
enum SystemPromptDefaultsHistory {

  /// Collapses whitespace runs and trims. Mirrors `normalized()` in the generator script.
  static func normalized(_ text: String) -> String {
    text.split(whereSeparator: { $0.isWhitespace || $0.isNewline }).joined(separator: " ")
  }

  static func fingerprint(_ text: String) -> String {
    SHA256.hash(data: Data(normalized(text).utf8)).map { String(format: "%02x", $0) }.joined()
  }

  /// The current default for a section — the text an unedited section is lifted to.
  static func currentDefault(for section: SystemPromptSection) -> String {
    switch section {
    case .dictation: return AppConstants.defaultTranscriptionSystemPrompt
    case .whisperGlossary: return AppConstants.defaultWhisperGlossary
    case .promptMode: return AppConstants.defaultPromptModeSystemPrompt
    case .chat: return AppConstants.defaultChatSystemPrompt
    case .readAloudRewrite: return AppConstants.defaultReadAloudRewritePrompt
    }
  }

  /// True when `text` is, modulo whitespace, some default this app has ever shipped for `section`.
  static func isShippedDefault(
    _ text: String, for section: SystemPromptSection,
    in history: [SystemPromptSection: Set<String>] = shippedFingerprints
  ) -> Bool {
    history[section]?.contains(fingerprint(text)) == true
  }

  /// Sections whose content is a former shipped default, mapped to the current default. Sections
  /// already on the current wording, edited by the user, or missing are not included.
  /// `shippedFingerprints` is injectable for tests only.
  static func upgrades(
    for sections: [SystemPromptSection: String],
    shippedFingerprints history: [SystemPromptSection: Set<String>] = shippedFingerprints
  ) -> [SystemPromptSection: String] {
    var result: [SystemPromptSection: String] = [:]
    for (section, content) in sections {
      let current = currentDefault(for: section)
      guard normalized(content) != normalized(current), isShippedDefault(content, for: section, in: history)
      else { continue }
      result[section] = current
    }
    return result
  }

  /// Newest first. Includes the current default so a section on the current wording also
  /// reads as "never edited" (relevant for the next time the default changes).
  static let shippedFingerprints: [SystemPromptSection: Set<String>] = [
    .dictation: [
      "7c2eef87377517af4421469b2e59e59b3c8209e1d369292efbd47f0efac18326",
      "b0dd47740cf7817f5eeebf2278618ec9b8d2f3d8b4872a12b9ce04ad12d29d49",
      "dff5482e5e9ba6fe0927a9714d4d2194f4344da0b98a9330c95228c5af76a970",
      "f6e07f9cc4f20bffbe617ffbfa881bc93e7f00e802dee1fd32c8ae5572025119",
      "e72e45fc953a8fbcf5002558c0cddd2fc07eced53987e2c5af004e7ceb53ece6",
      "56b4181208cb5b075da05045e92d44f5dddc1fe52f6a82e94e79aed6651c4871",
      "a37002896998a9ef257307520c4382db0dd66312393d23bf55d69f7a8f2f8a04",
      "8d690c87a74ea80741d42e9d3172c693bc039356f8aa7a6328c1b3054e2704d4",
      "11ddf78bce7cd155a1a1cfefa7f22166d40fa7c701327e3ae5fe89433c95a62d",
      "6630657df5f0f089314f0adecc7725732d3674eb6cf2f504871e4caa158d05a3",
      "de53ab831cc1859da7b8f52b8bd8bedc22df25618317e9cbd9eba1a4fb7094e3",
      "1b16dfe39f41bd0a2e996974062ca6b8ab86497130d069b5e3f87d96bd21e281",
      "22d2ed9e8a452717ba3abcb108f196b78a3e0ea4d91c3db4169c667776061942",
      "a3cd15d098a413a40e3ee8d073a69559227f52e24884648164d95b222fb92ed2",
      "3a338a5111c0eacfc67dfd8b5b214dee7ffe29e0044c4e001b9259c18385a1a7",
      "843ff3645c09f23be19a29d6edc2f4f87a92b85be30f12499563125e7f831b18",
    ],
    .whisperGlossary: [
      "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    ],
    .promptMode: [
      "de0fe1e16899304ac9a386472ba9f1e0ccfdda827870d8bc2eef91a519dcc8d8",
      "ea53b0e8d0a914224aa6e83a436c6d46b45e31c30f340022635584cb70cba39c",
      "9ed51c62f80518f367dc0ac6ce6ee79131a957e3ee4b4f116b715a71f31f2f73",
      "1017d065c63a05f593dfa11d9d6baa7510b6ee75b08036e583fc763a06785d5a",
      "13298c382f9ff205d13ee71fafdbb9c92c291ddfef1f885bb224412e05bc5dc7",
      "ad83d27c46da9e372e788fafe47074a766be8a0da0cb8d9577aa541351c32a1f",
      "9d89e4492a24471394cac7195e7d642db8b77d3c850f6537f44fc0931b45fde9",
      "70e92f294fe49c2b4ed4b067b1a945b135d240c5e21aba56a0031b23e656b30f",
      "f70715320311f65321f7ef53ec70f3440efd9fd1783aa07a38a5c5cb1fc18f0a",
      "383b4459003742f5514e8d081a1c54302b5163d89fd4bfee6bdb8656cf300391",
      "1d6ae4d411abd57072e4c807f2f69ec5f2e5995aa94fd2af94579f2d4849e51e",
      "1d2bacfd2d81f9814fbe4b707898185919054a322a5e46a013d79c76c4ef423b",
      "ed270d6684c60837c86c29a7c1eb795d0513cb6c302a9ba4a733d3a1210e0edb",
      "64c180148f943e6e640fb8f987b4c764d089b8fba477c0299f632ce6880d9196",
      "bc3e3e16d0dbe5268f3cfb2003d67256a8980aa6ba9cf187d57828058096c9ab",
      "2ae33f60f05ebce2946da679023326236a93a275da1b09af866fc57c71b6b560",
      "4c69e7e36e05c01f9a656760e271a47cc40052e177b8d1023ad831fb5ea5d153",
      "cc118b0119637707d503a43231d5ca32ac622c7802e0ee6b92e28ff637219796",
      "7506154dbdeea0372ef89ecfd3a9327f518de9de6119eea3e1b12a8f05a0ece2",
    ],
    .chat: [
      "b63b18caf0379f0c76233563e44ad1301ab703515bd5761fb4cc61cce49928b4",
      "32460af44df42508e6c2385acebd3eb82a1ed3759e3e8f66e1a04d61e4ef580d",
      "c87a724b57973033aca6ee1fd1028024d33f20b47ddc557ca711c413238f8d39",
      "5c33dffe5a72a26894e2438e3be69f60e330e64dc0fa169d22320f166480528e",
      "213d630c3d8b7ea569b6685d5b108a7be9b8f967194c784eb3ac915eae78ea9e",
      "55bc8d07c52890a636064858b378d5c0284649ba8a15a7643d3ba0c22c055c46",
      "08e74c467eee01663f5c469af9e7954fafd0bf35b5e8064ec5a9e0fe5ec01586",
      "c473739d09b620a31b0451c0f2d638380cb9e8727194cf64a3c64a7914441853",
      "63aec131c65809bc7e37e240d5181be4080f0193760376ff2114cdee52dc81c9",
      "356e84b038813fdc6ff7457b6948b15a818494982c60d765cc7cc6cecfb28545",
      "a58c9dffb6b061f1e3bc7e678da3998833dae771ec9cd733e3eb4843c4e1d112",
      "57fb29c5af81ca695ed0a80a3583a38a24ee51838d788ff5ef49a7c0db8e19c9",
    ],
    .readAloudRewrite: [
      "e926270ddf6a625b91abeea726861087fb3ae933582c01450bf9558742d64bd8",
      "70e310697aca107f145b6e5689d9b2ce9d7a0af2d9184a6e48f1866acd859d96",
      "f6139a28d1a00b1512d67d53572287ed7540729e7854f8affb14a03fb38fb922",
      "2dbe151e3d2e2a2fe7c26695c9f9970e08282dce2ae9b7f565b30f5c9fab6a16",
      "ab5bd9bddf1227af2c9b908e35540e5bfd0e60076856eee8574146ea37a97b6f",
    ],
  ]
}
