#!/usr/bin/env python3
"""Regenerates the shipped-default fingerprints in
WhisperShortcut/SystemPromptDefaultsHistory.swift from git history.

Every wording a `AppConstants.default*Prompt` constant has ever had is fingerprinted
(SHA-256 of the whitespace-normalised text). SystemPromptsStore uses the list to tell
"the user never touched this section" from "the user edited it": a section that still
equals any former default is lifted to the current one on launch.

Run after changing one of the default prompt constants, then commit the regenerated
Swift file. The test `SystemPromptDefaultsHistoryTests` fails until you do.

    python3 scripts/prompt-default-fingerprints.py
"""
import hashlib, re, subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONSTANTS = ROOT / "WhisperShortcut" / "AppConstants.swift"
OUT = ROOT / "WhisperShortcut" / "SystemPromptDefaultsHistory.swift"

# (Swift section case, constant name)
SECTIONS = [
    ("dictation", "defaultTranscriptionSystemPrompt"),
    ("whisperGlossary", "defaultWhisperGlossary"),
    ("promptMode", "defaultPromptModeSystemPrompt"),
    ("chat", "defaultChatSystemPrompt"),
    ("readAloudRewrite", "defaultReadAloudRewritePrompt"),
]


def normalized(text: str) -> str:
    # Must match SystemPromptDefaultsHistory.normalized in Swift.
    return re.sub(r"\s+", " ", text).strip()


def fingerprint(text: str) -> str:
    return hashlib.sha256(normalized(text).encode("utf-8")).hexdigest()


def extract(src: str, name: str):
    m = re.search(
        r"static let %s\s*=\s*(?:\n\s*)?(\"\"\"\n(.*?)\n\s*\"\"\"|\"((?:[^\"\\]|\\.)*)\")" % name,
        src, re.S)
    if not m:
        return None
    return m.group(2) if m.group(2) is not None else m.group(3)


def git(*args):
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, check=True).stdout


def main():
    # Working tree first (uncommitted edits count), then every commit that touched the file.
    sources = [("working tree", CONSTANTS.read_text())]
    for sha in git("log", "--format=%H", "--", "WhisperShortcut/AppConstants.swift").split():
        sources.append((sha[:8], git("show", f"{sha}:WhisperShortcut/AppConstants.swift")))

    per_section = {case: [] for case, _ in SECTIONS}  # ordered, newest first, unique
    for label, src in sources:
        for case, name in SECTIONS:
            text = extract(src, name)
            if text is None:
                continue
            fp = fingerprint(text)
            if fp not in per_section[case]:
                per_section[case].append(fp)

    lines = [
        "//",
        "//  SystemPromptDefaultsHistory.swift",
        "//  WhisperShortcut",
        "//",
        "//  GENERATED by scripts/prompt-default-fingerprints.py — do not edit by hand.",
        "//  Re-run the script after changing any AppConstants.default*Prompt constant.",
        "//",
        "",
        "import CryptoKit",
        "import Foundation",
        "",
        "/// Every wording the shipped default system prompts have ever had, as fingerprints.",
        "///",
        "/// `SystemPromptsStore` materialises the defaults into the user's `system-prompts.md` on first",
        "/// launch and reads only that file afterwards, so a change to a default constant never reached",
        "/// an existing install — even one whose user had not touched the section. This list is how the",
        "/// store tells \"never edited\" (still equal to some former default) from \"edited\": the former is",
        "/// lifted to the current default on launch, the latter is left alone.",
        "///",
        "/// Fingerprints are SHA-256 over whitespace-normalised text, so a stray trailing newline or",
        "/// re-wrapped paragraph in the file does not count as a user edit.",
        "enum SystemPromptDefaultsHistory {",
        "",
        "  /// Collapses whitespace runs and trims. Mirrors `normalized()` in the generator script.",
        "  static func normalized(_ text: String) -> String {",
        "    text.split(whereSeparator: { $0.isWhitespace || $0.isNewline }).joined(separator: \" \")",
        "  }",
        "",
        "  static func fingerprint(_ text: String) -> String {",
        "    SHA256.hash(data: Data(normalized(text).utf8)).map { String(format: \"%02x\", $0) }.joined()",
        "  }",
        "",
        "  /// The current default for a section — the text an unedited section is lifted to.",
        "  static func currentDefault(for section: SystemPromptSection) -> String {",
        "    switch section {",
    ]
    for case, name in SECTIONS:
        lines.append(f"    case .{case}: return AppConstants.{name}")
    lines += [
        "    }",
        "  }",
        "",
        "  /// True when `text` is, modulo whitespace, some default this app has ever shipped for `section`.",
        "  static func isShippedDefault(",
        "    _ text: String, for section: SystemPromptSection,",
        "    in history: [SystemPromptSection: Set<String>] = shippedFingerprints",
        "  ) -> Bool {",
        "    history[section]?.contains(fingerprint(text)) == true",
        "  }",
        "",
        "  /// Sections whose content is a former shipped default, mapped to the current default. Sections",
        "  /// already on the current wording, edited by the user, or missing are not included.",
        "  /// `shippedFingerprints` is injectable for tests only.",
        "  static func upgrades(",
        "    for sections: [SystemPromptSection: String],",
        "    shippedFingerprints history: [SystemPromptSection: Set<String>] = shippedFingerprints",
        "  ) -> [SystemPromptSection: String] {",
        "    var result: [SystemPromptSection: String] = [:]",
        "    for (section, content) in sections {",
        "      let current = currentDefault(for: section)",
        "      guard normalized(content) != normalized(current), isShippedDefault(content, for: section, in: history)",
        "      else { continue }",
        "      result[section] = current",
        "    }",
        "    return result",
        "  }",
        "",
        "  /// Newest first. Includes the current default so a section on the current wording also",
        "  /// reads as \"never edited\" (relevant for the next time the default changes).",
        "  static let shippedFingerprints: [SystemPromptSection: Set<String>] = [",
    ]
    for case, _ in SECTIONS:
        lines.append(f"    .{case}: [")
        for fp in per_section[case]:
            lines.append(f"      \"{fp}\",")
        lines.append("    ],")
    lines += ["  ]", "}", ""]
    OUT.write_text("\n".join(lines))
    total = sum(len(v) for v in per_section.values())
    print(f"wrote {OUT.relative_to(ROOT)}: {total} fingerprints across {len(SECTIONS)} sections")
    for case, fps in per_section.items():
        print(f"  {case}: {len(fps)}")


if __name__ == "__main__":
    main()
